### ISSUE TITLE
Instead of "ThreekitProvider" could we just call it "Threekit"?

### ISSUE THREAD

**Issue by bhouston** [Threekit/react-threekit#19]
Basically "ThreekitProvider" is a configuration instance with all its related data.  Maybe we could just call it "Threekit"?

**Comment by asaeed2** [comment]
Works for me.

**Comment by bhouston** [comment]
Is this because this is a Context.Provider class which one uses with createContext?  I guess then maybe it should be a Provider?

I guess I am a little confused by the pattern.  I thought that if you used a ContextProvider you'd have to create it first using React.createContext() but I suspect maybe you have wrapped that into the library....

**Comment by asaeed2** [comment]
It is a context provider (Redux toolkit instead of React context) that has just been abstracted along with a few other operations that go into its setup. The whole project is structured around the Provider pattern, where the presentational UI components use the hooks to interact with the context provider state which interacts with the Threekit JS API.

**Comment by bhouston** [comment]
Then it probably should stay provider.  I was wrong here clearly.

**Comment by bhouston** [comment]
In React hooks it generally seems to follow the pattern <Threekit.Provider>. Maybe that is what we should do?
